spring:
  profiles:
    active: dev
---
server:
  port: 8001

mybatis:
  type-aliases-package: com.test.springcloud.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

spring:
  profiles: dev
  application:
    name: springcloud-config-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: testspringcloud
    password: ZYL6fAyFG5kfCMcc
    url: jdbc:mysql://106.14.135.230:3306/testspringcloud?useSSL=false&useUnicode=true&characterEncoding=UTF-8

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    instance:
      intance-id: springcloud-provider-dept8001
      prefer-ip-address: true

info:
  app.name: wdnmd-springcloud
  company.name: wocaoledou
  
  ---
server:
  port: 8001

mybatis:
  type-aliases-package: com.test.springcloud.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

spring:
  profiles: dev
  application:
    name: springcloud-config-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: testspringcloud2
    password: Ln5Z63b3Ne8pbihK
    url: jdbc:mysql://106.14.135.230:3306/testspringcloud2?useSSL=false&useUnicode=true&characterEncoding=UTF-8

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    instance:
      intance-id: springcloud-provider-dept8001
      prefer-ip-address: true

info:
  app.name: wdnmd-springcloud
  company.name: wocaoledou